import { mkdirSync } from 'node:fs';
mkdirSync('screenshots',{recursive:true});
import { chromium } from 'playwright';
import { mandelaProfile } from '../src/data/mandelaProfile.ts';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');
const p=mandelaProfile();p.autoSpeak=false;p.focusMusic=false;p.soundEffects=false;
await page.evaluate(p=>localStorage.setItem('genius-tutor-data',JSON.stringify({profiles:[p],version:1})),p);
await page.reload();await page.getByText('Mandela',{exact:true}).first().click();
await page.getByRole('heading',{name:/Dinosaur Rescue Academy/}).waitFor();
await page.waitForFunction(()=>[...document.querySelectorAll('.explorer-portal img')].length===9&&[...document.querySelectorAll('.explorer-portal img')].every(i=>i.complete&&i.naturalWidth>0));
await page.screenshot({path:'screenshots/mandela-home.png',fullPage:true});
await page.getByRole('button',{name:/First-grade field missions/}).click();
await page.getByRole('button',{name:/NC.1.OA.1 · Supply station/}).click();
await page.getByRole('textbox',{name:/Your field notes/}).fill('I used 12 counters and found four more.');
await page.getByRole('button',{name:'I tried this activity'}).click();
await page.getByText('Fieldwork saved.',{exact:false}).waitFor();
await page.screenshot({path:'screenshots/mandela-fieldwork.png',fullPage:true});
await page.getByRole('button',{name:'Return to base'}).click();await page.getByRole('button',{name:/Enter the 3D/}).click();
await page.locator('canvas').waitFor();await page.waitForTimeout(2000);
await page.screenshot({path:'screenshots/mandela-island.png',fullPage:true});
await page.locator('canvas').click(); await page.keyboard.down('w');
await page.getByRole('button',{name:'Read question',exact:false}).waitFor({timeout:20000});await page.keyboard.up('w');
const hasQuestion=await page.getByRole('button',{name:'Read question',exact:false}).isVisible();
await page.getByRole('button',{name:'Return to base'}).click();
await page.getByRole('button',{name:'Settings',exact:false}).first().click();await page.getByLabel('Friendly robot-zombie encounters').check();
await page.getByRole('button',{name:'Save settings'}).click();
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('genius-tutor-data')).profiles[0]);
console.log(JSON.stringify({errors,hasQuestion,fieldwork:saved.jurassicFieldwork,zombies:saved.jurassicZombies}));
await browser.close();if(errors.length||!hasQuestion||!saved.jurassicZombies)process.exit(1);
