// ============================================================
// Talking-head video cache (renderer side).
//
// Videos generated by D-ID are saved to disk once (via the Electron
// bridge) and keyed by tutorId + the exact spoken text. On replay we
// look up the saved file and play it INSTANTLY — no regeneration, no
// cost, no waiting. This is what makes pre-recorded lessons feel like
// real-time interaction.
//
// In a plain browser (no Electron bridge) caching is a no-op and the app
// falls back to live generation / portrait animation.
// ============================================================

interface Bridge {
  saveVideo?: (key: string, bytes: ArrayBuffer) => Promise<string | null>;
  getVideo?: (key: string) => Promise<string | null>;
  listVideos?: () => Promise<string[]>;
}

function bridge(): Bridge | undefined {
  return (window as unknown as { geniusTutor?: Bridge }).geniusTutor;
}

/** Stable short key from tutor id + spoken text. */
export function cacheKey(tutorId: string, text: string): string {
  const norm = text.trim().toLowerCase().replace(/\s+/g, ' ');
  let h = 5381;
  for (let i = 0; i < norm.length; i++) h = ((h << 5) + h + norm.charCodeAt(i)) >>> 0;
  return `${tutorId}_${h.toString(36)}`;
}

/** Return a playable gtvideo:// url for a cached clip, or null. */
export async function getCachedVideo(tutorId: string, text: string): Promise<string | null> {
  const b = bridge();
  if (!b?.getVideo) return null;
  try {
    return await b.getVideo(cacheKey(tutorId, text));
  } catch {
    return null;
  }
}

/** Save a video blob to the on-disk cache; returns playable url or null. */
export async function saveCachedVideo(
  tutorId: string,
  text: string,
  blob: Blob
): Promise<string | null> {
  const b = bridge();
  if (!b?.saveVideo) return null;
  try {
    const buf = await blob.arrayBuffer();
    return await b.saveVideo(cacheKey(tutorId, text), buf);
  } catch {
    return null;
  }
}

/** How many clips are cached (for the pre-record progress UI). */
export async function cachedCount(): Promise<number> {
  const b = bridge();
  if (!b?.listVideos) return 0;
  try {
    return (await b.listVideos()).length;
  } catch {
    return 0;
  }
}

export function cacheAvailable(): boolean {
  return !!bridge()?.saveVideo;
}
